// Code generated by "stringer -type=iqType"; DO NOT EDIT

package xmpp

import "fmt"

const _iqType_name = "getsetresulterror"

var _iqType_index = [...]uint8{0, 3, 6, 12, 17}

func (i iqType) String() string {
	if i < 0 || i >= iqType(len(_iqType_index)-1) {
		return fmt.Sprintf("iqType(%d)", i)
	}
	return _iqType_name[_iqType_index[i]:_iqType_index[i+1]]
}
