// Code generated by "genfeature -vars=FeatureEscaping:`jid\20escaping`"; DO NOT EDIT.

package jid

import (
	"mellium.im/xmpp/disco/info"
)

// A list of service discovery features that are supported by this package.
var (
	FeatureEscaping = info.Feature{Var: `jid\20escaping`}
)
