// Code generated by "genfeature"; DO NOT EDIT.

package form

import (
	"mellium.im/xmpp/disco/info"
)

// A list of service discovery features that are supported by this package.
var (
	Feature = info.Feature{Var: NS}
)
