// Code generated by "stringer -type=NoteType -linecomment"; DO NOT EDIT.

package commands

import "strconv"

const _NoteType_name = "infowarnerror"

var _NoteType_index = [...]uint8{0, 4, 8, 13}

func (i NoteType) String() string {
	if i < 0 || i >= NoteType(len(_NoteType_index)-1) {
		return "NoteType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NoteType_name[_NoteType_index[i]:_NoteType_index[i+1]]
}
