// Code generated by "stringer -type=errorType -output stanzatype_string.go"; DO NOT EDIT

package stanza

import "fmt"

const _errorTypeName = "CancelAuthContinueModifyWait"

var _errorTypeIndex = [...]uint8{0, 6, 10, 18, 24, 28}

func (i errorType) String() string {
	if i < 0 || i >= errorType(len(_errorTypeIndex)-1) {
		return fmt.Sprintf("errorType(%d)", i)
	}
	return _errorTypeName[_errorTypeIndex[i]:_errorTypeIndex[i+1]]
}
