// Code generated by "stringer -type=iqType,errorType,messageType,presenceType -output stanzatype_string.go"; DO NOT EDIT

package stanza

import "fmt"

const _iqTypeName = "GetIQSetIQResultIQErrorIQ"

var _iqTypeIndex = [...]uint8{0, 5, 10, 18, 25}

func (i iqType) String() string {
	if i < 0 || i >= iqType(len(_iqTypeIndex)-1) {
		return fmt.Sprintf("iqType(%d)", i)
	}
	return _iqTypeName[_iqTypeIndex[i]:_iqTypeIndex[i+1]]
}

const _errorTypeName = "CancelAuthContinueModifyWait"

var _errorTypeIndex = [...]uint8{0, 6, 10, 18, 24, 28}

func (i errorType) String() string {
	if i < 0 || i >= errorType(len(_errorTypeIndex)-1) {
		return fmt.Sprintf("errorType(%d)", i)
	}
	return _errorTypeName[_errorTypeIndex[i]:_errorTypeIndex[i+1]]
}

const _messageTypeName = "NormalMessageChatMessageErrorMessageGroupChatMessageHeadlineMessage"

var _messageTypeIndex = [...]uint8{0, 13, 24, 36, 52, 67}

func (i messageType) String() string {
	if i < 0 || i >= messageType(len(_messageTypeIndex)-1) {
		return fmt.Sprintf("messageType(%d)", i)
	}
	return _messageTypeName[_messageTypeIndex[i]:_messageTypeIndex[i+1]]
}

const _presenceTypeName = "NoTypePresenceErrorPresenceProbePresenceSubscribePresenceSubscribedPresenceUnavailablePresenceUnsubscribePresenceUnsubscribedPresence"

var _presenceTypeIndex = [...]uint8{0, 14, 27, 40, 57, 75, 94, 113, 133}

func (i presenceType) String() string {
	if i < 0 || i >= presenceType(len(_presenceTypeIndex)-1) {
		return fmt.Sprintf("presenceType(%d)", i)
	}
	return _presenceTypeName[_presenceTypeIndex[i]:_presenceTypeIndex[i+1]]
}
