// Code generated by "stringer -type=errorType,messageType -output stanzatype_string.go"; DO NOT EDIT

package stanza

import "fmt"

const _errorTypeName = "CancelAuthContinueModifyWait"

var _errorTypeIndex = [...]uint8{0, 6, 10, 18, 24, 28}

func (i errorType) String() string {
	if i < 0 || i >= errorType(len(_errorTypeIndex)-1) {
		return fmt.Sprintf("errorType(%d)", i)
	}
	return _errorTypeName[_errorTypeIndex[i]:_errorTypeIndex[i+1]]
}

const _messageTypeName = "NormalMessageChatMessageErrorMessageGroupChatMessageHeadlineMessage"

var _messageTypeIndex = [...]uint8{0, 13, 24, 36, 52, 67}

func (i messageType) String() string {
	if i < 0 || i >= messageType(len(_messageTypeIndex)-1) {
		return fmt.Sprintf("messageType(%d)", i)
	}
	return _messageTypeName[_messageTypeIndex[i]:_messageTypeIndex[i+1]]
}
