// Code generated by "stringer -type=Condition -linecomment"; DO NOT EDIT.

package saslerr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Aborted-1]
	_ = x[AccountDisabled-2]
	_ = x[CredentialsExpired-3]
	_ = x[EncryptionRequired-4]
	_ = x[IncorrectEncoding-5]
	_ = x[InvalidAuthzID-6]
	_ = x[InvalidMechanism-7]
	_ = x[MalformedRequest-8]
	_ = x[MechanismTooWeak-9]
	_ = x[NotAuthorized-10]
	_ = x[TemporaryAuthFailure-11]
}

const _Condition_name = "noneabortedaccount-disabledcredentials-expiredencryption-requiredincorrect-encodinginvalid-authzidinvalid-mechanismmalformed-requestmechanism-too-weaknot-authorizedtemporary-auth-failure"

var _Condition_index = [...]uint8{0, 4, 11, 27, 46, 65, 83, 98, 115, 132, 150, 164, 186}

func (i Condition) String() string {
	if i >= Condition(len(_Condition_index)-1) {
		return "Condition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Condition_name[_Condition_index[i]:_Condition_index[i+1]]
}
