// Code generated by "genpubsub"; DO NOT EDIT.

package pubsub

import (
	"encoding/xml"
)

// Condition is the underlying cause of a pubsub error.
type Condition uint32

// Valid pubsub Conditions.
const (
	ErrNone                   Condition = iota
	ErrClosedNode                       // closed-node
	ErrConfigRequired                   // configuration-required
	ErrInvalidJID                       // invalid-jid
	ErrInvalidOptions                   // invalid-options
	ErrInvalidPayload                   // invalid-payload
	ErrInvalidSubID                     // invalid-subid
	ErrItemForbidden                    // item-forbidden
	ErrItemRequired                     // item-required
	ErrJIDRequired                      // jid-required
	ErrMaxItemsExceeded                 // max-items-exceeded
	ErrMaxNodesExceeded                 // max-nodes-exceeded
	ErrNodeIDRequired                   // nodeid-required
	ErrNotInRosterGroup                 // not-in-roster-group
	ErrNotSubscribed                    // not-subscribed
	ErrPayloadTooBig                    // payload-too-big
	ErrPayloadRequired                  // payload-required
	ErrPendingSubscription              // pending-subscription
	ErrPresenceRequired                 // presence-subscription-required
	ErrSubIDRequired                    // subid-required
	ErrTooManySubscriptions             // too-many-subscriptions
	ErrUnsupported                      // unsupported
	ErrUnsupportedAccessModel           // unsupported-access-model
)

// UnmarshalXML implements xml.Unmarshaler.
func (c *Condition) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for cond := ErrNone; cond <= ErrUnsupportedAccessModel; cond++ {
		if cond.String() == start.Name.Local {
			*c = cond
			break
		}
	}
	return d.Skip()
}

// Feature is a specific pubsub feature that may be reported in an error as
// being unsupported.
type Feature uint32

// Valid pubsub Features.
const (
	FeatureAccessAuthorize           Feature = iota // access-authorize
	FeatureAccessOpen                               // access-open
	FeatureAccessPresence                           // access-presence
	FeatureAccessRoster                             // access-roster
	FeatureAccessWhitelist                          // access-whitelist
	FeatureAutoCreate                               // auto-create
	FeatureAutoSubscribe                            // auto-subscribe
	FeatureCollections                              // collections
	FeatureConfigNode                               // config-node
	FeatureCreateAndConfigure                       // create-and-configure
	FeatureCreateNodes                              // create-nodes
	FeatureDeleteItems                              // delete-items
	FeatureDeleteNodes                              // delete-nodes
	FeatureFilteredNotifications                    // filtered-notifications
	FeatureGetPending                               // get-pending
	FeatureInstantNodes                             // instant-nodes
	FeatureItemIDs                                  // item-ids
	FeatureLastPublished                            // last-published
	FeatureLeasedSubscription                       // leased-subscription
	FeatureManageSubscriptions                      // manage-subscriptions
	FeatureMemberAffiliation                        // member-affiliation
	FeatureMetaData                                 // meta-data
	FeatureModifyAffiliations                       // modify-affiliations
	FeatureMultiCollection                          // multi-collection
	FeatureMultiSubscribe                           // multi-subscribe
	FeatureOutcastAffiliation                       // outcast-affiliation
	FeaturePersistentItems                          // persistent-items
	FeaturePresenceNotifications                    // presence-notifications
	FeaturePresenceSubscribe                        // presence-subscribe
	FeaturePublish                                  // publish
	FeaturePublishOptions                           // publish-options
	FeaturePublishOnlyAffiliation                   // publish-only-affiliation
	FeaturePublisherAffiliation                     // publisher-affiliation
	FeaturePurgeNodes                               // purge-nodes
	FeatureRetractItems                             // retract-items
	FeatureRetrieveAffiliations                     // retrieve-affiliations
	FeatureRetrieveDefault                          // retrieve-default
	FeatureRetrieveItems                            // retrieve-items
	FeatureRetrieveSubscriptions                    // retrieve-subscriptions
	FeatureSubscribe                                // subscribe
	FeatureSubscriptionOptions                      // subscription-options
	FeatureSubscriptionNotifications                // subscription-notifications
)

// SubType represents the state of a particular subscription.
type SubType uint8

// A list of possible subscription types.
const (
	SubNone         SubType = iota // none
	SubPending                     // pending
	SubSubscribed                  // subscribed
	SubUnconfigured                // unconfigured
)
