# TODO: re-enable sendxmpp, mcabber, and ejabberd
# See: https://mellium.im/issue/68, https://mellium.im/issue/222

pipeline:
  info: &info
    image: golang:alpine
    environment:
      GO111MODULE: "on"
      CGO_ENABLED: "0"
    commands:
      - go version
      - go env
  test:
    << : *info
    commands:
      - |
        cat > /etc/apk/repositories << EOF; $$(echo)

        http://dl-cdn.alpinelinux.org/alpine/v$$(cat /etc/alpine-release | cut -d'.' -f1,2)/main
        http://dl-cdn.alpinelinux.org/alpine/v$$(cat /etc/alpine-release | cut -d'.' -f1,2)/community
        http://dl-cdn.alpinelinux.org/alpine/edge/testing

        EOF
      - apk update
      - |
        apk add py3-slixmpp py3-aioxmpp \
                openssl prosody
      - python3 --version
      - go test -v -tags "integration" -run Integration ./...

depends_on:
  - dco
  - test
