pipeline:
  info: &info
    image: golang:${GO_VERSION}-alpine
    environment:
      GO111MODULE: "on"
      CGO_ENABLED: "0"
    commands:
      - go version
      - go env
  stable:
    << : *info
    commands: go test -v -cover ./...
  examples:
    << : *info
    commands: |
      cd examples/
      for d in ./*/; do
        cd $d
        go build
        cd ..
      done

matrix:
  GO_VERSION:
    - 1.17
    - 1.16

depends_on:
  - dco
