// Code generated by "genfeature -filename features.go -receiver h *discoHandler -vars Feature:NSInfo"; DO NOT EDIT.

package disco

import (
	"mellium.im/xmpp/disco/info"
)

// A list of service discovery features that are supported by this package.
var (
	Feature = info.Feature{Var: NSInfo}
)

// ForFeatures implements info.FeatureIter.
func (h *discoHandler) ForFeatures(node string, f func(info.Feature) error) error {
	if node != "" {
		return nil
	}
	var err error
	err = f(Feature)
	if err != nil {
		return err
	}
	return nil
}
