// Code generated by "stringer -type=Style"; DO NOT EDIT.

package styling

import "strconv"

const _Style_name = "BlockPreBlockQuoteSpanEmphSpanStrongSpanStrikeSpanPreBlockPreStartBlockPreEndBlockQuoteStartBlockQuoteEndSpanEmphStartSpanEmphEndSpanStrongStartSpanStrongEndSpanStrikeStartSpanStrikeEndSpanPreStartSpanPreEnd"

var _Style_map = map[Style]string{
	1:      _Style_name[0:8],
	2:      _Style_name[8:18],
	4:      _Style_name[18:26],
	8:      _Style_name[26:36],
	16:     _Style_name[36:46],
	32:     _Style_name[46:53],
	64:     _Style_name[53:66],
	128:    _Style_name[66:77],
	256:    _Style_name[77:92],
	512:    _Style_name[92:105],
	1024:   _Style_name[105:118],
	2048:   _Style_name[118:129],
	4096:   _Style_name[129:144],
	8192:   _Style_name[144:157],
	16384:  _Style_name[157:172],
	32768:  _Style_name[172:185],
	65536:  _Style_name[185:197],
	131072: _Style_name[197:207],
}

func (i Style) String() string {
	if str, ok := _Style_map[i]; ok {
		return str
	}
	return "Style(" + strconv.FormatInt(int64(i), 10) + ")"
}
